### ISSUE TITLE
Socket IO will not compile Linux UE4 4.23.0 - Async issue

### ISSUE THREAD

**Issue by joelelrocker** [getnamo/socketio-client-unreal#207]
How do you get this to compile on Linux? Specifically on 4.23.0? I receive an Async error every time.

socketio-client-ue4/Source/CoreUtility/Private/CUBlueprintLibrary.cpp:251:9: error: no matching function for call to 'Async'
        return Async(EAsyncExecution::Thread, [InBytes]
               ^~~~~
./Runtime/Core/Public/Async/Async.h:306:21: note: candidate template ignored: could not match 'TFunction<type-parameter-0-0 ()>' against '(lambda at /home/agent-joel-bot/Desktop/ue4/UnrealEngine-implement_buffer_swap_on_linux/Engine/Plugins/Runtime/socketio-client-ue4/Source/CoreUtility/Private/CUBlueprintLibrary.cpp:251:40)'
TFuture<ResultType> Async(EAsyncExecution Execution, TFunction<ResultType()> Function, TFunction<void()> CompletionCallback = TFunction<void()>())

**Comment by getnamo** [comment]
Not sure about linux at 4.23, it definitely does compile on 4.25. That said the latest tested 4.23 build would be the 1.2.0 branch: https://github.com/getnamo/socketio-client-ue4/tree/1.2.0. Pull to that point and try again.

**Comment by joelelrocker** [comment]
Thanks, I'll give it a try

**Comment by getnamo** [comment]
Closing due to age, re-open if problem persists in new plugin versions.
